name: stubtest

on: push

jobs:
  stubtestjob:
    name: Nextflow stub test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Runs a set of commands using the runners shell
      - name: install nextflow
        run: |
          curl -s https://get.nextflow.io | bash
          ./nextflow -version
      
      # Hope this runs after the previous step...
      - name: run nextflow test
        run: ./nextflow run main.nf -stub-run