name: stubtest

on: push

jobs:
  stubtestjob:
    name: Nextflow stub test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Runs a set of commands using the runners shell
      - name: install nextflow
        run: |
          curl -s https://get.nextflow.io | bash
          ./nextflow -version
      
      - name: run nextflow test for each module
        run: ./nextflow run main.nf -stub-run
      
      - name: run nextflow test for one wrapped module
        run: ./nextflow run main.nf -stub-run --wrap